import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/footer";
import { CartProvider } from "./(pages)/context/cartcontext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <CartProvider>
          {children}
        </CartProvider>
       <Footer/>
        </body>
    </html>
  );
}
