import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/footer";
import { CartProvider } from "./(pages)/context/cartcontext";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <CartProvider>
            <div className="content-wrapper">{children}</div>
            <Footer />
          </CartProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
